[package]
name = "totp_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", features = ["persistence"] }
serde = { version = "1", features = ["derive"] }
ring = "0.16"
base32 = "0.5.1"